"""deleted registered_at, last_login_at, is_active, source in User

Revision ID: 95c10821b426
Revises: bdc551062b4a
Create Date: 2025-11-04 07:07:54.558011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95c10821b426'
down_revision: Union[str, Sequence[str], None] = 'bdc551062b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_active')
    op.drop_column('User', 'last_login_at')
    op.drop_column('User', 'source')
    op.drop_column('User', 'registered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
