"""add UserSubscription

Revision ID: a1aed6f63184
Revises: ef0cb6081af7
Create Date: 2025-10-27 15:30:32.982438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1aed6f63184'
down_revision: Union[str, Sequence[str], None] = 'ef0cb6081af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserSubscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.CheckConstraint('(expires_at IS NULL) OR (expires_at >= started_at)', name='chk_subscription_time_valid'),
    sa.ForeignKeyConstraint(['subscription_id'], ['Subscription.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserSubscription_user_id'), 'UserSubscription', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserSubscription_user_id'), table_name='UserSubscription')
    op.drop_table('UserSubscription')
    # ### end Alembic commands ###
