"""Fix nullable in User birthday_date. Set True

Revision ID: 92552ded4334
Revises: d62d0b28a428
Create Date: 2025-09-24 08:47:17.998126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92552ded4334'
down_revision: Union[str, Sequence[str], None] = 'd62d0b28a428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'birthday_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'birthday_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
