"""new user

Revision ID: 42cf3d5c5afd
Revises: 92552ded4334
Create Date: 2025-10-27 14:50:44.086408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42cf3d5c5afd'
down_revision: Union[str, Sequence[str], None] = '92552ded4334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('User', sa.Column('email', sa.String(length=256), nullable=True))
    op.add_column('User', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_active')
    op.drop_column('User', 'email')
    op.drop_column('User', 'phone')
    # ### end Alembic commands ###
