"""Add source and laguage in User model

Revision ID: bdc551062b4a
Revises: 1d60d906fd49
Create Date: 2025-11-03 18:39:34.415386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc551062b4a'
down_revision: Union[str, Sequence[str], None] = '1d60d906fd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'language')
    op.drop_column('User', 'source')
    # ### end Alembic commands ###
